import { HistoryItem } from "@/types";
import { MaintenanceType, ExpenseCategory } from "@prisma/client";

export const FakeHistory: HistoryItem[] = [
  {
    id: "1",
    kind: "maintenance",
    type: MaintenanceType.OIL_CHANGE,
    vehicle: "Toyota Corolla",
    cost: 89,
    date: "01/06/2026",
    km: 25000,
  },
  {
    id: "2",
    kind: "expense",
    type: ExpenseCategory.FUEL,
    vehicle: "Honda Civic",
    cost: 72,
    date: "05/06/2026",
    km: 30000,
  },
  {
    id: "3",
    kind: "maintenance",
    type: MaintenanceType.REVISION,
    vehicle: "Ford Focus",
    cost: 210,
    date: "05/03/2024",
    km: 15000,
  },
  {
    id: "4",
    kind: "maintenance",
    type: MaintenanceType.BRAKE,
    vehicle: "Toyota Corolla",
    cost: 145,
    date: "20/02/2024",
    km: 24000,
  },
  {
    id: "5",
    kind: "maintenance",
    type: MaintenanceType.BATTERY,
    vehicle: "Honda Civic",
    cost: 130,
    date: "14/02/2024",
    km: 29500,
  },
  {
    id: "6",
    kind: "maintenance",
    type: MaintenanceType.BELT,
    vehicle: "Ford Focus",
    cost: 95,
    date: "01/01/2024",
    km: 14200,
  },
  {
    id: "7",
    kind: "maintenance",
    type: MaintenanceType.FILTER,
    vehicle: "Toyota Corolla",
    cost: 45,
    date: "10/12/2023",
    km: 23000,
  },
  {
    id: "8",
    kind: "maintenance",
    type: MaintenanceType.CONTROL,
    vehicle: "Honda Civic",
    cost: 79,
    date: "05/12/2023",
    km: 29000,
  },
  {
    id: "9",
    kind: "maintenance",
    type: MaintenanceType.OTHER,
    vehicle: "Ford Focus",
    cost: 60,
    date: "28/11/2023",
    km: 13800,
  },
  {
    id: "10",
    kind: "expense",
    type: ExpenseCategory.FUEL,
    vehicle: "Toyota Corolla",
    cost: 72,
    date: "15/05/2024",
    km: 25000,
  },
  {
    id: "11",
    kind: "expense",
    type: ExpenseCategory.INSURANCE,
    vehicle: "Honda Civic",
    cost: 520,
    date: "01/01/2024",
    km: 29000,
  },
  {
    id: "12",
    kind: "expense",
    type: ExpenseCategory.PARKING,
    vehicle: "Ford Focus",
    cost: 15,
    date: "10/04/2024",
    km: 15000,
  },
  {
    id: "13",
    kind: "expense",
    type: ExpenseCategory.TOLL,
    vehicle: "Toyota Corolla",
    cost: 8,
    date: "20/02/2024",
    km: 24000,
  },
  {
    id: "14",
    kind: "expense",
    type: ExpenseCategory.FINE,
    vehicle: "Honda Civic",
    cost: 135,
    date: "14/02/2024",
    km: 29500,
  },
  {
    id: "15",
    kind: "expense",
    type: ExpenseCategory.WASH,
    vehicle: "Ford Focus",
    cost: 35,
    date: "05/12/2023",
    km: 13800,
  },
  {
    id: "16",
    kind: "expense",
    type: ExpenseCategory.OTHER,
    vehicle: "Toyota Corolla",
    cost: 50,
    date: "28/11/2023",
    km: 22500,
  },
  {
    id: "17",
    kind: "expense",
    type: ExpenseCategory.OTHER,
    vehicle: "Toyota Corolla",
    cost: 50,
    date: "02/06/2026",
    km: 22500,
  },
];
