import { HistoryItem } from "@/types";
import { MaintenanceType, ExpenseCategory } from "@prisma/client";
import { Calendar, DollarSign, Fuel, Wrench, Zap } from "lucide-react";

export const FakeVehicles = [
  {
    id: "1",
    name: "Ma Camry",
    brand: "Toyota",
    model: "Camry",
    year: 2020,
    plate: "ABC-123",
    km: 50000,

    lastService: "01/06",
    totalCost: 1500,
  },
  {
    id: "2",
    name: "Ma Civic",
    brand: "Honda",
    model: "Civic",
    year: 2019,
    plate: "DEF-456",
    km: 30000,

    lastService: "05/06",
    totalCost: 72,
  },
  {
    id: "3",
    name: "Ma Focus",
    brand: "Ford",
    model: "Focus",
    year: 2018,
    plate: "GHI-789",
    km: 40000,

    lastService: "05/03",
    totalCost: 210,
  },
];

export const FakeHistory: HistoryItem[] = [
  {
    id: "1",
    kind: "maintenance",
    type: MaintenanceType.OIL_CHANGE,
    vehicleId: "1",
    cost: 89,
    date: "2026-06-01",
    km: 25000,
  },
  {
    id: "2",
    kind: "expense",
    type: ExpenseCategory.FUEL,
    vehicleId: "2",
    cost: 72,
    date: "2026-06-05",
  },
  {
    id: "3",
    kind: "maintenance",
    type: MaintenanceType.REVISION,
    vehicleId: "3",
    cost: 210,
    date: "2024-03-05",
    km: 15000,
  },
  {
    id: "4",
    kind: "maintenance",
    type: MaintenanceType.BRAKE,
    vehicleId: "1",
    cost: 145,
    date: "2024-02-20",
    km: 24000,
  },
  {
    id: "5",
    kind: "maintenance",
    type: MaintenanceType.BATTERY,
    vehicleId: "2",
    cost: 130,
    date: "2024-02-14",
    km: 29500,
  },
  {
    id: "6",
    kind: "maintenance",
    type: MaintenanceType.BELT,
    vehicleId: "3",
    cost: 95,
    date: "2024-01-01",
    km: 14200,
  },
  {
    id: "7",
    kind: "maintenance",
    type: MaintenanceType.FILTER,
    vehicleId: "1",
    cost: 45,
    date: "2023-12-10",
    km: 23000,
  },
  {
    id: "8",
    kind: "maintenance",
    type: MaintenanceType.CONTROL,
    vehicleId: "2",
    cost: 79,
    date: "2023-12-05",
    km: 29000,
  },
  {
    id: "9",
    kind: "maintenance",
    type: MaintenanceType.OTHER,
    vehicleId: "3",
    cost: 60,
    date: "2023-11-28",
    km: 13800,
  },
  {
    id: "10",
    kind: "expense",
    type: ExpenseCategory.FUEL,
    vehicleId: "1",
    cost: 72,
    date: "2024-05-15",
  },
  {
    id: "11",
    kind: "expense",
    type: ExpenseCategory.INSURANCE,
    vehicleId: "2",
    cost: 520,
    date: "2024-01-01",
  },
  {
    id: "12",
    kind: "expense",
    type: ExpenseCategory.PARKING,
    vehicleId: "3",
    cost: 15,
    date: "2024-04-10",
  },
  {
    id: "13",
    kind: "expense",
    type: ExpenseCategory.TOLL,
    vehicleId: "1",
    cost: 8,
    date: "2024-02-20",
  },
  {
    id: "14",
    kind: "expense",
    type: ExpenseCategory.FINE,
    vehicleId: "2",
    cost: 135,
    date: "2024-02-14",
  },
  {
    id: "15",
    kind: "expense",
    type: ExpenseCategory.WASH,
    vehicleId: "3",
    cost: 35,
    date: "2023-12-05",
  },
  {
    id: "16",
    kind: "expense",
    type: ExpenseCategory.OTHER,
    vehicleId: "1",
    cost: 50,
    date: "2023-11-28",
  },
  {
    id: "17",
    kind: "expense",
    type: ExpenseCategory.OTHER,
    vehicleId: "1",
    cost: 50,
    date: "2026-06-02",
  },
];

export const FakeNotifications = [
  {
    id: 1,
    unread: true,
    icon: Wrench,
    color: "bg-amber-50 text-amber-600",
    title: "Révision à prévoir",
    body: "Peugeot 308 approche de son échéance de révision (45 000 km).",
    time: "À l'instant",
    category: "entretien",
  },
  {
    id: 2,
    unread: true,
    icon: Fuel,
    color: "bg-blue-50 text-blue-600",
    title: "Seuil kilométrique atteint",
    body: "Renault Clio a franchi les 62 000 km. Pensez à vérifier les filtres.",
    time: "2h",
    category: "alerte",
  },
  {
    id: 3,
    unread: true,
    icon: DollarSign,
    color: "bg-green-50 text-green-600",
    title: "Résumé mai 2025",
    body: "Total dépenses : 939 € sur 3 véhicules. Voir le détail.",
    time: "1j",
    category: "résumé",
  },
  {
    id: 4,
    unread: false,
    icon: Calendar,
    color: "bg-purple-50 text-purple-600",
    title: "Contrôle technique",
    body: "BMW 320d — contrôle technique à renouveler avant le 15 juillet 2025.",
    time: "3j",
    category: "alerte",
  },
  {
    id: 5,
    unread: false,
    icon: Zap,
    color: "bg-neutral-100 text-neutral-600",
    title: "Nouveauté MyDriveLog",
    body: "Vous pouvez maintenant exporter votre historique en CSV directement depuis l'historique.",
    time: "5j",
    category: "info",
  },
  {
    id: 6,
    unread: false,
    icon: Wrench,
    color: "bg-amber-50 text-amber-600",
    title: "Vidange effectuée",
    body: "Peugeot 308 — vidange enregistrée le 12 mai. Prochain rappel dans 10 000 km.",
    time: "8j",
    category: "entretien",
  },
];

export const VehicleOptions = FakeVehicles.map((v) => ({
  value: v.id,
  label: v.name,
}));
